// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace HappyCoding.JsonInSqlServer.Scenario3.Migrations
{
    [DbContext(typeof(Scenario3DbContext))]
    partial class Scenario2DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HappyCoding.JsonInSqlServer.Scenario2.ModelWithJsonData2", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("JsonData")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("ReducedPropertySize")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Timestamp1")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Timestamp2")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("TestingTable");
                });
#pragma warning restore 612, 618
        }
    }
}
