// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RemovedEnumMember/MyTestMessageUpdated.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HappyCoding.ProtobufSerialization.CompatibleModificationsTests.RemovedEnumMember {

  /// <summary>Holder for reflection information generated from RemovedEnumMember/MyTestMessageUpdated.proto</summary>
  public static partial class MyTestMessageUpdatedReflection {

    #region Descriptor
    /// <summary>File descriptor for RemovedEnumMember/MyTestMessageUpdated.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MyTestMessageUpdatedReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CixSZW1vdmVkRW51bU1lbWJlci9NeVRlc3RNZXNzYWdlVXBkYXRlZC5wcm90",
            "byKiAQoUTXlUZXN0TWVzc2FnZVVwZGF0ZWQSEQoJZmlyc3ROYW1lGAEgASgJ",
            "EhAKCGxhc3ROYW1lGAIgASgJEgsKA2FnZRgDIAEoBRIOCgZlbWFpbHMYBCAD",
            "KAkSSAobcHJlZmVycmVkV2F5T2ZDb21tdW5pY2F0aW9uGAUgASgOMiMuUHJl",
            "ZmVycmVkV2F5T2ZDb21tdW5pY2F0aW9uVXBkYXRlZCpKCiJQcmVmZXJyZWRX",
            "YXlPZkNvbW11bmljYXRpb25VcGRhdGVkEg8KC1VOU1BFQ0lGSUVEEAASCQoF",
            "UEhPTkUQAhIICgRQT1NUEANCU6oCUEhhcHB5Q29kaW5nLlByb3RvYnVmU2Vy",
            "aWFsaXphdGlvbi5Db21wYXRpYmxlTW9kaWZpY2F0aW9uc1Rlc3RzLlJlbW92",
            "ZWRFbnVtTWVtYmVyYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::HappyCoding.ProtobufSerialization.CompatibleModificationsTests.RemovedEnumMember.PreferredWayOfCommunicationUpdated), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::HappyCoding.ProtobufSerialization.CompatibleModificationsTests.RemovedEnumMember.MyTestMessageUpdated), global::HappyCoding.ProtobufSerialization.CompatibleModificationsTests.RemovedEnumMember.MyTestMessageUpdated.Parser, new[]{ "FirstName", "LastName", "Age", "Emails", "PreferredWayOfCommunication" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum PreferredWayOfCommunicationUpdated {
    [pbr::OriginalName("UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("PHONE")] Phone = 2,
    [pbr::OriginalName("POST")] Post = 3,
  }

  #endregion

  #region Messages
  public sealed partial class MyTestMessageUpdated : pb::IMessage<MyTestMessageUpdated>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MyTestMessageUpdated> _parser = new pb::MessageParser<MyTestMessageUpdated>(() => new MyTestMessageUpdated());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MyTestMessageUpdated> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HappyCoding.ProtobufSerialization.CompatibleModificationsTests.RemovedEnumMember.MyTestMessageUpdatedReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MyTestMessageUpdated() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MyTestMessageUpdated(MyTestMessageUpdated other) : this() {
      firstName_ = other.firstName_;
      lastName_ = other.lastName_;
      age_ = other.age_;
      emails_ = other.emails_.Clone();
      preferredWayOfCommunication_ = other.preferredWayOfCommunication_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MyTestMessageUpdated Clone() {
      return new MyTestMessageUpdated(this);
    }

    /// <summary>Field number for the "firstName" field.</summary>
    public const int FirstNameFieldNumber = 1;
    private string firstName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FirstName {
      get { return firstName_; }
      set {
        firstName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "lastName" field.</summary>
    public const int LastNameFieldNumber = 2;
    private string lastName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LastName {
      get { return lastName_; }
      set {
        lastName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "age" field.</summary>
    public const int AgeFieldNumber = 3;
    private int age_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Age {
      get { return age_; }
      set {
        age_ = value;
      }
    }

    /// <summary>Field number for the "emails" field.</summary>
    public const int EmailsFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_emails_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> emails_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Emails {
      get { return emails_; }
    }

    /// <summary>Field number for the "preferredWayOfCommunication" field.</summary>
    public const int PreferredWayOfCommunicationFieldNumber = 5;
    private global::HappyCoding.ProtobufSerialization.CompatibleModificationsTests.RemovedEnumMember.PreferredWayOfCommunicationUpdated preferredWayOfCommunication_ = global::HappyCoding.ProtobufSerialization.CompatibleModificationsTests.RemovedEnumMember.PreferredWayOfCommunicationUpdated.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HappyCoding.ProtobufSerialization.CompatibleModificationsTests.RemovedEnumMember.PreferredWayOfCommunicationUpdated PreferredWayOfCommunication {
      get { return preferredWayOfCommunication_; }
      set {
        preferredWayOfCommunication_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MyTestMessageUpdated);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MyTestMessageUpdated other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FirstName != other.FirstName) return false;
      if (LastName != other.LastName) return false;
      if (Age != other.Age) return false;
      if(!emails_.Equals(other.emails_)) return false;
      if (PreferredWayOfCommunication != other.PreferredWayOfCommunication) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FirstName.Length != 0) hash ^= FirstName.GetHashCode();
      if (LastName.Length != 0) hash ^= LastName.GetHashCode();
      if (Age != 0) hash ^= Age.GetHashCode();
      hash ^= emails_.GetHashCode();
      if (PreferredWayOfCommunication != global::HappyCoding.ProtobufSerialization.CompatibleModificationsTests.RemovedEnumMember.PreferredWayOfCommunicationUpdated.Unspecified) hash ^= PreferredWayOfCommunication.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FirstName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FirstName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LastName);
      }
      if (Age != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Age);
      }
      emails_.WriteTo(output, _repeated_emails_codec);
      if (PreferredWayOfCommunication != global::HappyCoding.ProtobufSerialization.CompatibleModificationsTests.RemovedEnumMember.PreferredWayOfCommunicationUpdated.Unspecified) {
        output.WriteRawTag(40);
        output.WriteEnum((int) PreferredWayOfCommunication);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FirstName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FirstName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LastName);
      }
      if (Age != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Age);
      }
      emails_.WriteTo(ref output, _repeated_emails_codec);
      if (PreferredWayOfCommunication != global::HappyCoding.ProtobufSerialization.CompatibleModificationsTests.RemovedEnumMember.PreferredWayOfCommunicationUpdated.Unspecified) {
        output.WriteRawTag(40);
        output.WriteEnum((int) PreferredWayOfCommunication);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FirstName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FirstName);
      }
      if (LastName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LastName);
      }
      if (Age != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Age);
      }
      size += emails_.CalculateSize(_repeated_emails_codec);
      if (PreferredWayOfCommunication != global::HappyCoding.ProtobufSerialization.CompatibleModificationsTests.RemovedEnumMember.PreferredWayOfCommunicationUpdated.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PreferredWayOfCommunication);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MyTestMessageUpdated other) {
      if (other == null) {
        return;
      }
      if (other.FirstName.Length != 0) {
        FirstName = other.FirstName;
      }
      if (other.LastName.Length != 0) {
        LastName = other.LastName;
      }
      if (other.Age != 0) {
        Age = other.Age;
      }
      emails_.Add(other.emails_);
      if (other.PreferredWayOfCommunication != global::HappyCoding.ProtobufSerialization.CompatibleModificationsTests.RemovedEnumMember.PreferredWayOfCommunicationUpdated.Unspecified) {
        PreferredWayOfCommunication = other.PreferredWayOfCommunication;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FirstName = input.ReadString();
            break;
          }
          case 18: {
            LastName = input.ReadString();
            break;
          }
          case 24: {
            Age = input.ReadInt32();
            break;
          }
          case 34: {
            emails_.AddEntriesFrom(input, _repeated_emails_codec);
            break;
          }
          case 40: {
            PreferredWayOfCommunication = (global::HappyCoding.ProtobufSerialization.CompatibleModificationsTests.RemovedEnumMember.PreferredWayOfCommunicationUpdated) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            FirstName = input.ReadString();
            break;
          }
          case 18: {
            LastName = input.ReadString();
            break;
          }
          case 24: {
            Age = input.ReadInt32();
            break;
          }
          case 34: {
            emails_.AddEntriesFrom(ref input, _repeated_emails_codec);
            break;
          }
          case 40: {
            PreferredWayOfCommunication = (global::HappyCoding.ProtobufSerialization.CompatibleModificationsTests.RemovedEnumMember.PreferredWayOfCommunicationUpdated) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
