// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MyTestMessageWithTimestamps.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HappyCoding.ProtobufSerialization.UsingGoogleProtobuf.Data {

  /// <summary>Holder for reflection information generated from MyTestMessageWithTimestamps.proto</summary>
  public static partial class MyTestMessageWithTimestampsReflection {

    #region Descriptor
    /// <summary>File descriptor for MyTestMessageWithTimestamps.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MyTestMessageWithTimestampsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFNeVRlc3RNZXNzYWdlV2l0aFRpbWVzdGFtcHMucHJvdG8aH2dvb2dsZS9w",
            "cm90b2J1Zi90aW1lc3RhbXAucHJvdG8izwEKG015VGVzdE1lc3NhZ2VXaXRo",
            "VGltZXN0YW1wcxISCgpmaXJzdF9uYW1lGAEgASgJEhEKCWxhc3RfbmFtZRgC",
            "IAEoCRILCgNhZ2UYAyABKAUSDgoGZW1haWxzGAQgAygJEjQKEG15X3RpbWVz",
            "dGFtcF91dGMYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjYK",
            "Em15X3RpbWVzdGFtcF9sb2NhbBgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5U",
            "aW1lc3RhbXBCPaoCOkhhcHB5Q29kaW5nLlByb3RvYnVmU2VyaWFsaXphdGlv",
            "bi5Vc2luZ0dvb2dsZVByb3RvYnVmLkRhdGFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::HappyCoding.ProtobufSerialization.UsingGoogleProtobuf.Data.MyTestMessageWithTimestamps), global::HappyCoding.ProtobufSerialization.UsingGoogleProtobuf.Data.MyTestMessageWithTimestamps.Parser, new[]{ "FirstName", "LastName", "Age", "Emails", "MyTimestampUtc", "MyTimestampLocal" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MyTestMessageWithTimestamps : pb::IMessage<MyTestMessageWithTimestamps>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MyTestMessageWithTimestamps> _parser = new pb::MessageParser<MyTestMessageWithTimestamps>(() => new MyTestMessageWithTimestamps());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MyTestMessageWithTimestamps> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HappyCoding.ProtobufSerialization.UsingGoogleProtobuf.Data.MyTestMessageWithTimestampsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MyTestMessageWithTimestamps() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MyTestMessageWithTimestamps(MyTestMessageWithTimestamps other) : this() {
      firstName_ = other.firstName_;
      lastName_ = other.lastName_;
      age_ = other.age_;
      emails_ = other.emails_.Clone();
      myTimestampUtc_ = other.myTimestampUtc_ != null ? other.myTimestampUtc_.Clone() : null;
      myTimestampLocal_ = other.myTimestampLocal_ != null ? other.myTimestampLocal_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MyTestMessageWithTimestamps Clone() {
      return new MyTestMessageWithTimestamps(this);
    }

    /// <summary>Field number for the "first_name" field.</summary>
    public const int FirstNameFieldNumber = 1;
    private string firstName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FirstName {
      get { return firstName_; }
      set {
        firstName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "last_name" field.</summary>
    public const int LastNameFieldNumber = 2;
    private string lastName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LastName {
      get { return lastName_; }
      set {
        lastName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "age" field.</summary>
    public const int AgeFieldNumber = 3;
    private int age_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Age {
      get { return age_; }
      set {
        age_ = value;
      }
    }

    /// <summary>Field number for the "emails" field.</summary>
    public const int EmailsFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_emails_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> emails_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Emails {
      get { return emails_; }
    }

    /// <summary>Field number for the "my_timestamp_utc" field.</summary>
    public const int MyTimestampUtcFieldNumber = 5;
    private global::Google.Protobuf.WellKnownTypes.Timestamp myTimestampUtc_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp MyTimestampUtc {
      get { return myTimestampUtc_; }
      set {
        myTimestampUtc_ = value;
      }
    }

    /// <summary>Field number for the "my_timestamp_local" field.</summary>
    public const int MyTimestampLocalFieldNumber = 6;
    private global::Google.Protobuf.WellKnownTypes.Timestamp myTimestampLocal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp MyTimestampLocal {
      get { return myTimestampLocal_; }
      set {
        myTimestampLocal_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MyTestMessageWithTimestamps);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MyTestMessageWithTimestamps other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FirstName != other.FirstName) return false;
      if (LastName != other.LastName) return false;
      if (Age != other.Age) return false;
      if(!emails_.Equals(other.emails_)) return false;
      if (!object.Equals(MyTimestampUtc, other.MyTimestampUtc)) return false;
      if (!object.Equals(MyTimestampLocal, other.MyTimestampLocal)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FirstName.Length != 0) hash ^= FirstName.GetHashCode();
      if (LastName.Length != 0) hash ^= LastName.GetHashCode();
      if (Age != 0) hash ^= Age.GetHashCode();
      hash ^= emails_.GetHashCode();
      if (myTimestampUtc_ != null) hash ^= MyTimestampUtc.GetHashCode();
      if (myTimestampLocal_ != null) hash ^= MyTimestampLocal.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FirstName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FirstName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LastName);
      }
      if (Age != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Age);
      }
      emails_.WriteTo(output, _repeated_emails_codec);
      if (myTimestampUtc_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(MyTimestampUtc);
      }
      if (myTimestampLocal_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(MyTimestampLocal);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FirstName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FirstName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LastName);
      }
      if (Age != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Age);
      }
      emails_.WriteTo(ref output, _repeated_emails_codec);
      if (myTimestampUtc_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(MyTimestampUtc);
      }
      if (myTimestampLocal_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(MyTimestampLocal);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FirstName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FirstName);
      }
      if (LastName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LastName);
      }
      if (Age != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Age);
      }
      size += emails_.CalculateSize(_repeated_emails_codec);
      if (myTimestampUtc_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MyTimestampUtc);
      }
      if (myTimestampLocal_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MyTimestampLocal);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MyTestMessageWithTimestamps other) {
      if (other == null) {
        return;
      }
      if (other.FirstName.Length != 0) {
        FirstName = other.FirstName;
      }
      if (other.LastName.Length != 0) {
        LastName = other.LastName;
      }
      if (other.Age != 0) {
        Age = other.Age;
      }
      emails_.Add(other.emails_);
      if (other.myTimestampUtc_ != null) {
        if (myTimestampUtc_ == null) {
          MyTimestampUtc = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        MyTimestampUtc.MergeFrom(other.MyTimestampUtc);
      }
      if (other.myTimestampLocal_ != null) {
        if (myTimestampLocal_ == null) {
          MyTimestampLocal = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        MyTimestampLocal.MergeFrom(other.MyTimestampLocal);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FirstName = input.ReadString();
            break;
          }
          case 18: {
            LastName = input.ReadString();
            break;
          }
          case 24: {
            Age = input.ReadInt32();
            break;
          }
          case 34: {
            emails_.AddEntriesFrom(input, _repeated_emails_codec);
            break;
          }
          case 42: {
            if (myTimestampUtc_ == null) {
              MyTimestampUtc = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(MyTimestampUtc);
            break;
          }
          case 50: {
            if (myTimestampLocal_ == null) {
              MyTimestampLocal = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(MyTimestampLocal);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            FirstName = input.ReadString();
            break;
          }
          case 18: {
            LastName = input.ReadString();
            break;
          }
          case 24: {
            Age = input.ReadInt32();
            break;
          }
          case 34: {
            emails_.AddEntriesFrom(ref input, _repeated_emails_codec);
            break;
          }
          case 42: {
            if (myTimestampUtc_ == null) {
              MyTimestampUtc = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(MyTimestampUtc);
            break;
          }
          case 50: {
            if (myTimestampLocal_ == null) {
              MyTimestampLocal = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(MyTimestampLocal);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
