// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MyTestMessageWithOneOf.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HappyCoding.ProtobufSerialization.UsingGoogleProtobuf.Data {

  /// <summary>Holder for reflection information generated from MyTestMessageWithOneOf.proto</summary>
  public static partial class MyTestMessageWithOneOfReflection {

    #region Descriptor
    /// <summary>File descriptor for MyTestMessageWithOneOf.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MyTestMessageWithOneOfReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxNeVRlc3RNZXNzYWdlV2l0aE9uZU9mLnByb3RvIpcBChZNeVRlc3RNZXNz",
            "YWdlV2l0aE9uZU9mEhIKCmZpcnN0X25hbWUYASABKAkSEQoJbGFzdF9uYW1l",
            "GAIgASgJEgsKA2FnZRgDIAEoBRIeChRjb250YWN0X21haWxfYWRkcmVzcxgF",
            "IAEoCUgAEh4KFGNvbnRhY3RfcGhvbmVfbnVtYmVyGAYgASgJSABCCQoHQ29u",
            "dGFjdEI9qgI6SGFwcHlDb2RpbmcuUHJvdG9idWZTZXJpYWxpemF0aW9uLlVz",
            "aW5nR29vZ2xlUHJvdG9idWYuRGF0YWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::HappyCoding.ProtobufSerialization.UsingGoogleProtobuf.Data.MyTestMessageWithOneOf), global::HappyCoding.ProtobufSerialization.UsingGoogleProtobuf.Data.MyTestMessageWithOneOf.Parser, new[]{ "FirstName", "LastName", "Age", "ContactMailAddress", "ContactPhoneNumber" }, new[]{ "Contact" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MyTestMessageWithOneOf : pb::IMessage<MyTestMessageWithOneOf>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MyTestMessageWithOneOf> _parser = new pb::MessageParser<MyTestMessageWithOneOf>(() => new MyTestMessageWithOneOf());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MyTestMessageWithOneOf> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HappyCoding.ProtobufSerialization.UsingGoogleProtobuf.Data.MyTestMessageWithOneOfReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MyTestMessageWithOneOf() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MyTestMessageWithOneOf(MyTestMessageWithOneOf other) : this() {
      firstName_ = other.firstName_;
      lastName_ = other.lastName_;
      age_ = other.age_;
      switch (other.ContactCase) {
        case ContactOneofCase.ContactMailAddress:
          ContactMailAddress = other.ContactMailAddress;
          break;
        case ContactOneofCase.ContactPhoneNumber:
          ContactPhoneNumber = other.ContactPhoneNumber;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MyTestMessageWithOneOf Clone() {
      return new MyTestMessageWithOneOf(this);
    }

    /// <summary>Field number for the "first_name" field.</summary>
    public const int FirstNameFieldNumber = 1;
    private string firstName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FirstName {
      get { return firstName_; }
      set {
        firstName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "last_name" field.</summary>
    public const int LastNameFieldNumber = 2;
    private string lastName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LastName {
      get { return lastName_; }
      set {
        lastName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "age" field.</summary>
    public const int AgeFieldNumber = 3;
    private int age_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Age {
      get { return age_; }
      set {
        age_ = value;
      }
    }

    /// <summary>Field number for the "contact_mail_address" field.</summary>
    public const int ContactMailAddressFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ContactMailAddress {
      get { return contactCase_ == ContactOneofCase.ContactMailAddress ? (string) contact_ : ""; }
      set {
        contact_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        contactCase_ = ContactOneofCase.ContactMailAddress;
      }
    }

    /// <summary>Field number for the "contact_phone_number" field.</summary>
    public const int ContactPhoneNumberFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ContactPhoneNumber {
      get { return contactCase_ == ContactOneofCase.ContactPhoneNumber ? (string) contact_ : ""; }
      set {
        contact_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        contactCase_ = ContactOneofCase.ContactPhoneNumber;
      }
    }

    private object contact_;
    /// <summary>Enum of possible cases for the "Contact" oneof.</summary>
    public enum ContactOneofCase {
      None = 0,
      ContactMailAddress = 5,
      ContactPhoneNumber = 6,
    }
    private ContactOneofCase contactCase_ = ContactOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ContactOneofCase ContactCase {
      get { return contactCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearContact() {
      contactCase_ = ContactOneofCase.None;
      contact_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MyTestMessageWithOneOf);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MyTestMessageWithOneOf other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FirstName != other.FirstName) return false;
      if (LastName != other.LastName) return false;
      if (Age != other.Age) return false;
      if (ContactMailAddress != other.ContactMailAddress) return false;
      if (ContactPhoneNumber != other.ContactPhoneNumber) return false;
      if (ContactCase != other.ContactCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FirstName.Length != 0) hash ^= FirstName.GetHashCode();
      if (LastName.Length != 0) hash ^= LastName.GetHashCode();
      if (Age != 0) hash ^= Age.GetHashCode();
      if (contactCase_ == ContactOneofCase.ContactMailAddress) hash ^= ContactMailAddress.GetHashCode();
      if (contactCase_ == ContactOneofCase.ContactPhoneNumber) hash ^= ContactPhoneNumber.GetHashCode();
      hash ^= (int) contactCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FirstName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FirstName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LastName);
      }
      if (Age != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Age);
      }
      if (contactCase_ == ContactOneofCase.ContactMailAddress) {
        output.WriteRawTag(42);
        output.WriteString(ContactMailAddress);
      }
      if (contactCase_ == ContactOneofCase.ContactPhoneNumber) {
        output.WriteRawTag(50);
        output.WriteString(ContactPhoneNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FirstName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FirstName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LastName);
      }
      if (Age != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Age);
      }
      if (contactCase_ == ContactOneofCase.ContactMailAddress) {
        output.WriteRawTag(42);
        output.WriteString(ContactMailAddress);
      }
      if (contactCase_ == ContactOneofCase.ContactPhoneNumber) {
        output.WriteRawTag(50);
        output.WriteString(ContactPhoneNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FirstName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FirstName);
      }
      if (LastName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LastName);
      }
      if (Age != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Age);
      }
      if (contactCase_ == ContactOneofCase.ContactMailAddress) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ContactMailAddress);
      }
      if (contactCase_ == ContactOneofCase.ContactPhoneNumber) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ContactPhoneNumber);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MyTestMessageWithOneOf other) {
      if (other == null) {
        return;
      }
      if (other.FirstName.Length != 0) {
        FirstName = other.FirstName;
      }
      if (other.LastName.Length != 0) {
        LastName = other.LastName;
      }
      if (other.Age != 0) {
        Age = other.Age;
      }
      switch (other.ContactCase) {
        case ContactOneofCase.ContactMailAddress:
          ContactMailAddress = other.ContactMailAddress;
          break;
        case ContactOneofCase.ContactPhoneNumber:
          ContactPhoneNumber = other.ContactPhoneNumber;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FirstName = input.ReadString();
            break;
          }
          case 18: {
            LastName = input.ReadString();
            break;
          }
          case 24: {
            Age = input.ReadInt32();
            break;
          }
          case 42: {
            ContactMailAddress = input.ReadString();
            break;
          }
          case 50: {
            ContactPhoneNumber = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            FirstName = input.ReadString();
            break;
          }
          case 18: {
            LastName = input.ReadString();
            break;
          }
          case 24: {
            Age = input.ReadInt32();
            break;
          }
          case 42: {
            ContactMailAddress = input.ReadString();
            break;
          }
          case 50: {
            ContactPhoneNumber = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
