// <auto-generated />
using System;
using HappyCoding.JsonInSqlServer.Scenario1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HappyCoding.JsonInSqlServer.Scenario1.Migrations
{
    [DbContext(typeof(Scenario1DbContext))]
    partial class Scenario1DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HappyCoding.JsonInSqlServer.Scenario1.ModelWithJsonData", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JsonData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Timestamp1")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Timestamp2")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("TestingTable");
                });
#pragma warning restore 612, 618
        }
    }
}
