// <auto-generated />
using System;
using HappyCoding.HexagonalArchitecture.SQLiteAdapter;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HappyCoding.HexagonalArchitecture.SQLiteAdapter.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220718045642_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("HappyCoding.HexagonalArchitecture.Domain.Model.ProtocolEntry", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntryType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkshopID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("WorkshopID");

                    b.ToTable("Protocol", (string)null);
                });

            modelBuilder.Entity("HappyCoding.HexagonalArchitecture.Domain.Model.Workshop", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Workshop", (string)null);
                });

            modelBuilder.Entity("HappyCoding.HexagonalArchitecture.Domain.Model.ProtocolEntry", b =>
                {
                    b.HasOne("HappyCoding.HexagonalArchitecture.Domain.Model.Workshop", null)
                        .WithMany("Protocol")
                        .HasForeignKey("WorkshopID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HappyCoding.HexagonalArchitecture.Domain.Model.Workshop", b =>
                {
                    b.Navigation("Protocol");
                });
#pragma warning restore 612, 618
        }
    }
}
